# -*- coding: utf-8 -*-
"""Fraud Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rGzrB97gfSnpeKr8SATrV3WrHG7FeUqP
"""

# =========================
# Import Libraries
# =========================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.svm import OneClassSVM

data = pd.read_csv('creditcard.csv',sep=',')
data.head()

# =========================
# Basic Info
# =========================
print(data.info())
print(data['Class'].value_counts())

# =========================
# Class Distribution Plot
# =========================
sns.countplot(x='Class', data=data)
plt.title("Transaction Class Distribution (0 = Normal, 1 = Fraud)")
plt.show()

## Get the Fraud and the normal dataset

fraud = data[data['Class']==1]

normal = data[data['Class']==0]

print(fraud.shape,normal.shape)

## We need to analyze more amount of information from the transaction data
#How different are the amount of money used in different transaction classes?
fraud.Amount.describe()

normal.Amount.describe()

# =========================
# Improved Visualization (Scatter Plot FIXED)
# =========================
plt.figure(figsize=(10,6))
plt.scatter(normal.Time, normal.Amount, label="Normal", alpha=0.5)
plt.scatter(fraud.Time, fraud.Amount, label="Fraud", alpha=0.7, color='red')
plt.legend()
plt.xlabel("Time")
plt.ylabel("Amount")
plt.title("Transaction Time vs Amount")
plt.show()

# =========================
# Sampling
# =========================
data1 = data.sample(frac=0.1, random_state=42)

Fraud = data1[data1['Class'] == 1]
Valid = data1[data1['Class'] == 0]

outlier_fraction = len(Fraud) / float(len(Valid))

print("Outlier Fraction:", outlier_fraction)

# =========================
# Correlation Heatmap
# =========================
plt.figure(figsize=(12,10))
sns.heatmap(data1.corr(), cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

# =========================
# Prepare Data
# =========================
X = data1.drop('Class', axis=1)
Y = data1['Class']

# =========================
# Models
# =========================
classifiers = {
    "Isolation Forest": IsolationForest(
        n_estimators=100,
        contamination=outlier_fraction,
        random_state=42
    ),

    "Local Outlier Factor": LocalOutlierFactor(
        n_neighbors=20,
        contamination=outlier_fraction
    ),

    "One-Class SVM": OneClassSVM(
        kernel='rbf',
        gamma=0.1,
        nu=0.05
    )
}
outlier_fraction = len(Fraud)/float(len(Valid))

# =========================
# Training + Evaluation + Visualization
# =========================
results = {}

for name, clf in classifiers.items():

    if name == "Local Outlier Factor":
        y_pred = clf.fit_predict(X)
    else:
        clf.fit(X)
        y_pred = clf.predict(X)

    # Convert labels
    y_pred[y_pred == 1] = 0
    y_pred[y_pred == -1] = 1

    acc = accuracy_score(Y, y_pred)
    results[name] = acc

    print(f"\n{name}")
    print("Accuracy:", acc)
    print(classification_report(Y, y_pred))

    # =========================
    # Confusion Matrix Visualization
    # =========================
    cm = confusion_matrix(Y, y_pred)

    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title(f"{name} - Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

# =========================
# Model Comparison Plot
# =========================
plt.figure(figsize=(8,5))
plt.bar(results.keys(), results.values())
plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")
plt.xticks(rotation=20)
plt.show()







